export type FieldType = 'text' | 'textarea' | 'number' | 'toggle' | 'date' | 'json' | 'url' | 'select' | 'image';

export interface AdminField {
  name: string;
  label: string;
  type: FieldType;
  hint?: string;
  options?: { value: string; label: string }[];
}

export interface ResourceSchema {
  resource: string;
  title: string;
  singular: string;
  desc: string;
  fields: AdminField[];
  defaultNew: Record<string, unknown>;
  columns?: string[]; // kolom yang tampil di tabel list
}

export const RESOURCE_SCHEMAS: Record<string, ResourceSchema> = {
  projects: {
    resource: 'projects',
    title: 'Projects',
    singular: 'Project',
    desc: 'Kelola project portofolio',
    columns: ['thumbnail', 'title', 'category', 'status', 'featured', 'is_active'],
    fields: [
      { name: 'title', label: 'Judul', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Kosongkan untuk auto-generate' },
      { name: 'category', label: 'Kategori', type: 'text' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'tech_stack', label: 'Tech Stack', type: 'json', hint: 'Array JSON, contoh: ["Laravel","React"]' },
      { name: 'thumbnail', label: 'Thumbnail', type: 'image' },
      { name: 'github_url', label: 'GitHub URL', type: 'url' },
      { name: 'live_url', label: 'Live URL', type: 'url' },
      { name: 'status', label: 'Status', type: 'text', hint: 'contoh: completed, ongoing' },
      { name: 'featured', label: 'Featured', type: 'toggle' },
      { name: 'tags', label: 'Tags', type: 'json', hint: 'Array JSON' },
      { name: 'seo', label: 'SEO', type: 'json', hint: 'Contoh: {"meta_title":"...","meta_description":"..."}' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'difficulty', label: 'Kesulitan', type: 'text' },
      { name: 'completion', label: 'Progres (%)', type: 'number' },
    ],
    defaultNew: { is_active: true, featured: false, sort_order: 0 },
  },
  blogs: {
    resource: 'blogs',
    title: 'Blog / Posts',
    singular: 'Artikel',
    desc: 'Kelola artikel blog',
    columns: ['cover_image', 'title', 'category', 'status', 'featured', 'is_active'],
    fields: [
      { name: 'title', label: 'Judul', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Kosongkan untuk auto-generate' },
      { name: 'category', label: 'Kategori', type: 'text' },
      { name: 'excerpt', label: 'Ringkasan', type: 'textarea' },
      { name: 'content', label: 'Konten', type: 'textarea' },
      { name: 'cover_image', label: 'Cover', type: 'image' },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'published', label: 'Published' }, { value: 'draft', label: 'Draft' }] },
      { name: 'featured', label: 'Featured', type: 'toggle' },
      { name: 'tags', label: 'Tags', type: 'json', hint: 'Array JSON' },
      { name: 'seo', label: 'SEO', type: 'json' },
      { name: 'published_at', label: 'Tanggal Publikasi', type: 'date' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { status: 'draft', is_active: true, featured: false },
  },
  skills: {
    resource: 'skills',
    title: 'Skills',
    singular: 'Skill',
    desc: 'Kelola keahlian & level',
    columns: ['name', 'category', 'level', 'sort_order', 'is_active'],
    fields: [
      { name: 'name', label: 'Nama', type: 'text' },
      { name: 'category', label: 'Kategori', type: 'text' },
      { name: 'icon', label: 'Icon', type: 'text', hint: 'Nama kelas icon / emoji' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'level', label: 'Level (1-100)', type: 'number' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, sort_order: 0, level: 50 },
  },
  experience: {
    resource: 'experience',
    title: 'Experience',
    singular: 'Pengalaman',
    desc: 'Riwayat kerja',
    columns: ['company', 'title', 'start_date', 'end_date', 'is_current', 'is_active'],
    fields: [
      { name: 'title', label: 'Posisi', type: 'text' },
      { name: 'company', label: 'Perusahaan', type: 'text' },
      { name: 'location', label: 'Lokasi', type: 'text' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'achievements', label: 'Pencapaian', type: 'json', hint: 'Array JSON, contoh: ["Meningkatkan X"]' },
      { name: 'start_date', label: 'Mulai', type: 'date' },
      { name: 'end_date', label: 'Selesai', type: 'date' },
      { name: 'is_current', label: 'Masih bekerja di sini', type: 'toggle' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, is_current: false, sort_order: 0 },
  },
  education: {
    resource: 'education',
    title: 'Education',
    singular: 'Pendidikan',
    desc: 'Riwayat pendidikan',
    columns: ['institution', 'degree', 'start_date', 'end_date', 'is_active'],
    fields: [
      { name: 'institution', label: 'Institusi', type: 'text' },
      { name: 'degree', label: 'Gelar', type: 'text' },
      { name: 'field_of_study', label: 'Jurusan', type: 'text' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'start_date', label: 'Mulai', type: 'date' },
      { name: 'end_date', label: 'Selesai', type: 'date' },
      { name: 'is_current', label: 'Masih berkuliah', type: 'toggle' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, is_current: false, sort_order: 0 },
  },
  certificates: {
    resource: 'certificates',
    title: 'Certificates',
    singular: 'Sertifikat',
    desc: 'Sertifikasi & pelatihan',
    columns: ['title', 'issuer', 'issue_date', 'is_active'],
    fields: [
      { name: 'title', label: 'Nama Sertifikat', type: 'text' },
      { name: 'issuer', label: 'Penerbit', type: 'text' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'issue_date', label: 'Tanggal Terbit', type: 'date' },
      { name: 'expiry_date', label: 'Tanggal Kadaluarsa', type: 'date' },
      { name: 'credential_id', label: 'ID Kredensial', type: 'text' },
      { name: 'credential_url', label: 'URL Kredensial', type: 'url' },
      { name: 'image', label: 'Gambar', type: 'image' },
      { name: 'file', label: 'File', type: 'text' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, sort_order: 0 },
  },
  galleries: {
    resource: 'galleries',
    title: 'Galleries',
    singular: 'Album',
    desc: 'Album galeri foto',
    columns: ['cover_image', 'title', 'category', 'images', 'is_active'],
    fields: [
      { name: 'title', label: 'Judul', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Kosongkan untuk auto-generate' },
      { name: 'description', label: 'Deskripsi', type: 'textarea' },
      { name: 'category', label: 'Kategori', type: 'text' },
      { name: 'event_date', label: 'Tanggal Acara', type: 'date' },
      { name: 'location', label: 'Lokasi', type: 'text' },
      { name: 'cover_image', label: 'Cover', type: 'image' },
      { name: 'images', label: 'Foto', type: 'json', hint: 'Array path JSON' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, sort_order: 0 },
  },
  social: {
    resource: 'social',
    title: 'Social Media',
    singular: 'Media Sosial',
    desc: 'Link media sosial',
    columns: ['icon', 'platform', 'url', 'sort_order', 'is_active'],
    fields: [
      { name: 'platform', label: 'Platform', type: 'text' },
      { name: 'url', label: 'URL', type: 'url' },
      { name: 'icon', label: 'Icon', type: 'text' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, sort_order: 0 },
  },
  menu: {
    resource: 'menu',
    title: 'Menu',
    singular: 'Menu',
    desc: 'Navigasi menu situs',
    columns: ['name', 'url', 'sort_order', 'is_hidden', 'is_active'],
    fields: [
      { name: 'name', label: 'Nama', type: 'text' },
      { name: 'url', label: 'URL', type: 'text' },
      { name: 'icon', label: 'Icon', type: 'text' },
      { name: 'parent_id', label: 'Parent ID', type: 'number', hint: 'ID menu induk (0 = root)' },
      { name: 'sort_order', label: 'Urutan', type: 'number' },
      { name: 'is_hidden', label: 'Sembunyikan', type: 'toggle' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true, is_hidden: false, sort_order: 0, parent_id: 0 },
  },
  prompts: {
    resource: 'prompts',
    title: 'AI Prompts',
    singular: 'Prompt',
    desc: 'Template prompt untuk fitur AI',
    columns: ['name', 'category', 'is_active'],
    fields: [
      { name: 'name', label: 'Nama', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text', hint: 'Kosongkan untuk auto-generate' },
      { name: 'category', label: 'Kategori', type: 'text' },
      { name: 'prompt_text', label: 'Isi Prompt', type: 'textarea' },
      { name: 'variables', label: 'Variabel', type: 'json', hint: 'Object JSON, contoh: {"title":"Judul"}' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: true },
  },
  themes: {
    resource: 'themes',
    title: 'Themes',
    singular: 'Theme',
    desc: 'Tema visual situs',
    columns: ['name', 'is_active', 'dark_mode'],
    fields: [
      { name: 'name', label: 'Nama', type: 'text' },
      { name: 'primary_color', label: 'Primary Color', type: 'text', hint: 'Hex, contoh: #22d3ee' },
      { name: 'secondary_color', label: 'Secondary Color', type: 'text' },
      { name: 'accent_color', label: 'Accent Color', type: 'text' },
      { name: 'background_color', label: 'Background', type: 'text' },
      { name: 'text_color', label: 'Text Color', type: 'text' },
      { name: 'font_family', label: 'Font Family', type: 'text' },
      { name: 'glass_effect', label: 'Glass Effect', type: 'toggle' },
      { name: 'dark_mode', label: 'Dark Mode', type: 'toggle' },
      { name: 'custom_css', label: 'Custom CSS', type: 'json', hint: 'Dapat berupa JSON tema lanjutan' },
      { name: 'is_active', label: 'Aktif', type: 'toggle' },
    ],
    defaultNew: { is_active: false, dark_mode: true, glass_effect: true, primary_color: '#22d3ee' },
  },
  translations: {
    resource: 'translations',
    title: 'Translations',
    singular: 'Terjemahan',
    desc: 'Terjemahan multi bahasa',
    columns: ['key', 'locale', 'value', 'is_synced'],
    fields: [
      { name: 'key', label: 'Key', type: 'text' },
      { name: 'locale', label: 'Locale', type: 'text', hint: 'contoh: id, en, ja' },
      { name: 'value', label: 'Nilai', type: 'textarea' },
      { name: 'group', label: 'Grup', type: 'text' },
      { name: 'is_synced', label: 'Tersinkron', type: 'toggle' },
    ],
    defaultNew: { is_synced: true, group: 'general' },
  },
  contacts: {
    resource: 'contacts',
    title: 'Pesan Masuk',
    singular: 'Pesan',
    desc: 'Pesan dari form kontak publik',
    columns: ['name', 'email', 'subject', 'is_read', 'created_at'],
    fields: [
      { name: 'name', label: 'Nama', type: 'text' },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'subject', label: 'Subjek', type: 'text' },
      { name: 'message', label: 'Pesan', type: 'textarea' },
      { name: 'is_read', label: 'Sudah dibaca', type: 'toggle' },
    ],
    defaultNew: { is_read: false },
  },
};