-- Porto CMS — Supabase (Postgres) Schema — Part 1: Tables
-- Jalankan di Supabase Dashboard > SQL Editor (semua bagian dalam urutan)

-- Tables
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username varchar(255) unique,
  name varchar(255) not null,
  email varchar(255) not null unique,
  email_verified_at timestamptz,
  password varchar(255) not null,
  remember_token varchar(100),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key varchar(255) not null unique,
  value text,
  "group" varchar(255) not null default 'general',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.hero_sections (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  subtitle varchar(255),
  typing_texts jsonb,
  description text,
  background_type varchar(255) not null default 'gradient',
  background_value varchar(255),
  background_image varchar(255),
  photo varchar(255),
  buttons jsonb,
  social_media jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.about_sections (
  id bigint generated by default as identity primary key,
  photo varchar(255),
  description text,
  quote varchar(255),
  statistics jsonb,
  skills jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  tech_stack jsonb,
  category varchar(255),
  thumbnail varchar(255),
  thumbnail_prompt varchar(255),
  github_url varchar(255),
  live_url varchar(255),
  status varchar(255) not null default 'published',
  featured boolean not null default false,
  views integer not null default 0,
  seo jsonb,
  tags jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  icon varchar(255),
  category varchar(255),
  description text,
  level integer,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  company varchar(255) not null,
  location varchar(255),
  start_date date,
  end_date date,
  is_current boolean not null default false,
  description text,
  achievements jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  institution varchar(255) not null,
  degree varchar(255) not null,
  field_of_study varchar(255),
  start_date date,
  end_date date,
  is_current boolean not null default false,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  issuer varchar(255) not null,
  issue_date date,
  expiry_date date,
  description text,
  file varchar(255),
  image varchar(255),
  credential_id varchar(255),
  credential_url varchar(255),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  excerpt text,
  content text,
  cover_image varchar(255),
  tags jsonb,
  category varchar(255),
  status varchar(255) not null default 'published',
  featured boolean not null default false,
  views integer not null default 0,
  seo jsonb,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null,
  subject varchar(200),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz default now()
);

create table if not exists public.social_media (
  id bigint generated by default as identity primary key,
  platform varchar(255) not null,
  url varchar(255) not null,
  icon varchar(255),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  url varchar(255),
  icon varchar(255),
  parent_id integer,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  is_hidden boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.translations (
  id bigint generated by default as identity primary key,
  locale varchar(10) not null,
  "group" varchar(255) not null default '*',
  key varchar(255) not null,
  value text,
  is_synced boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (locale, "group", key)
);

create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  prompt_text text not null,
  category varchar(255),
  variables jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  file_path varchar(255) not null,
  file_type varchar(255) not null,
  mime_type varchar(255),
  file_size integer,
  disk varchar(255) not null default 'public',
  collection varchar(255),
  metadata jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action varchar(255) not null,
  subject_type varchar(255),
  subject_id bigint,
  properties jsonb,
  description text,
  ip_address varchar(45),
  user_agent varchar(255),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.seos (
  id bigint generated by default as identity primary key,
  meta_title varchar(255),
  meta_description text,
  meta_keywords text,
  og_image varchar(255),
  og_title varchar(255),
  og_description text,
  twitter_card varchar(255),
  canonical_url varchar(255),
  structured_data jsonb,
  subject_type varchar(255) not null,
  subject_id bigint not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (subject_type, subject_id)
);

create table if not exists public.themes (
  id bigint generated by default as identity primary key,
  name varchar(255) not null default 'default',
  is_active boolean not null default false,
  primary_color varchar(255) not null default '#3b82f6',
  secondary_color varchar(255) not null default '#8b5cf6',
  accent_color varchar(255) not null default '#06b6d4',
  gradient_start varchar(255) not null default '#3b82f6',
  gradient_end varchar(255) not null default '#8b5cf6',
  glow_color varchar(255) not null default '#3b82f6',
  dark_bg varchar(255) not null default '#0a0a1a',
  light_bg varchar(255) not null default '#ffffff',
  glass_effect boolean not null default true,
  animation_speed varchar(255) not null default 'normal',
  typography varchar(255) not null default 'inter',
  border_radius varchar(255) not null default '0.5rem',
  dark_mode boolean not null default true,
  custom_css jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.galleries (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  cover_image varchar(255),
  images jsonb,
  category varchar(255),
  location varchar(255),
  event_date date,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);