-- ============================================
-- PORTO CMS - Part 4: Contact form & view counters
-- Jalankan untuk database yang sudah ada (idempotent / aman dijalankan ulang)
-- ============================================

-- View counters untuk project & artikel
alter table public.projects add column if not exists views integer not null default 0;
alter table public.posts add column if not exists views integer not null default 0;

-- Pesan dari form kontak publik
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null,
  subject varchar(200),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz default now()
);

-- RLS aktif tanpa policy publik: hanya diakses via service role (Next.js server),
-- sehingga pesan & email pengunjung tidak terekspos ke publik.
alter table public.contacts enable row level security;

-- Index
create index if not exists contacts_created_at_index on public.contacts (created_at desc);
create index if not exists projects_views_index on public.projects (views desc);
create index if not exists posts_views_index on public.posts (views desc);
