-- ============================================================
-- 06 — SHOWCASE: foto full-bleed yang bisa dikelola dari owner
-- ============================================================
-- Jalankan di Supabase SQL Editor (setelah 01–05).
-- Tabel ini menggerakkan section "fit photo" di halaman utama:
-- owner bisa menambah foto + judul + posisi penempatannya.

create table if not exists public.showcase (
  id                bigint generated by default as identity primary key,
  title             text,
  subtitle          text,
  image             text,
  -- posisi penempatan section di halaman utama:
  --   after_hero       : setelah hero
  --   after_projects   : setelah featured projects
  --   after_experience : setelah experience
  --   after_blog       : setelah blog
  section_position  text not null default 'after_projects',
  is_active         boolean not null default true,
  sort_order        int not null default 0,
  created_at        timestamptz not null default now()
);

-- RLS: publik boleh baca, tulis hanya service role (sama seperti tabel lain)
alter table public.showcase enable row level security;

drop policy if exists "Public read showcase" on public.showcase;
create policy "Public read showcase"
  on public.showcase for select
  using (true);
