-- ============================================
-- PORTO CMS - FULL SETUP (run once in Supabase SQL Editor)
-- ============================================

/* ---- supabase\01-tables.sql ---- */

-- Porto CMS — Supabase (Postgres) Schema — Part 1: Tables
-- Jalankan di Supabase Dashboard > SQL Editor (semua bagian dalam urutan)

-- Tables
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username varchar(255) unique,
  name varchar(255) not null,
  email varchar(255) not null unique,
  email_verified_at timestamptz,
  password varchar(255) not null,
  remember_token varchar(100),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  key varchar(255) not null unique,
  value text,
  "group" varchar(255) not null default 'general',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.hero_sections (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  subtitle varchar(255),
  typing_texts jsonb,
  description text,
  background_type varchar(255) not null default 'gradient',
  background_value varchar(255),
  background_image varchar(255),
  photo varchar(255),
  buttons jsonb,
  social_media jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.about_sections (
  id bigint generated by default as identity primary key,
  photo varchar(255),
  description text,
  quote varchar(255),
  statistics jsonb,
  skills jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  tech_stack jsonb,
  category varchar(255),
  thumbnail varchar(255),
  thumbnail_prompt varchar(255),
  github_url varchar(255),
  live_url varchar(255),
  status varchar(255) not null default 'published',
  featured boolean not null default false,
  seo jsonb,
  tags jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  icon varchar(255),
  category varchar(255),
  description text,
  level integer,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.experiences (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  company varchar(255) not null,
  location varchar(255),
  start_date date,
  end_date date,
  is_current boolean not null default false,
  description text,
  achievements jsonb,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  institution varchar(255) not null,
  degree varchar(255) not null,
  field_of_study varchar(255),
  start_date date,
  end_date date,
  is_current boolean not null default false,
  description text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  issuer varchar(255) not null,
  issue_date date,
  expiry_date date,
  description text,
  file varchar(255),
  image varchar(255),
  credential_id varchar(255),
  credential_url varchar(255),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  excerpt text,
  content text,
  cover_image varchar(255),
  tags jsonb,
  category varchar(255),
  status varchar(255) not null default 'published',
  featured boolean not null default false,
  seo jsonb,
  published_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.social_media (
  id bigint generated by default as identity primary key,
  platform varchar(255) not null,
  url varchar(255) not null,
  icon varchar(255),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  url varchar(255),
  icon varchar(255),
  parent_id integer,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  is_hidden boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.translations (
  id bigint generated by default as identity primary key,
  locale varchar(10) not null,
  "group" varchar(255) not null default '*',
  key varchar(255) not null,
  value text,
  is_synced boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (locale, "group", key)
);

create table if not exists public.prompts (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  prompt_text text not null,
  category varchar(255),
  variables jsonb,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  file_path varchar(255) not null,
  file_type varchar(255) not null,
  mime_type varchar(255),
  file_size integer,
  disk varchar(255) not null default 'public',
  collection varchar(255),
  metadata jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete set null,
  action varchar(255) not null,
  subject_type varchar(255),
  subject_id bigint,
  properties jsonb,
  description text,
  ip_address varchar(45),
  user_agent varchar(255),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.seos (
  id bigint generated by default as identity primary key,
  meta_title varchar(255),
  meta_description text,
  meta_keywords text,
  og_image varchar(255),
  og_title varchar(255),
  og_description text,
  twitter_card varchar(255),
  canonical_url varchar(255),
  structured_data jsonb,
  subject_type varchar(255) not null,
  subject_id bigint not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (subject_type, subject_id)
);

create table if not exists public.themes (
  id bigint generated by default as identity primary key,
  name varchar(255) not null default 'default',
  is_active boolean not null default false,
  primary_color varchar(255) not null default '#3b82f6',
  secondary_color varchar(255) not null default '#8b5cf6',
  accent_color varchar(255) not null default '#06b6d4',
  gradient_start varchar(255) not null default '#3b82f6',
  gradient_end varchar(255) not null default '#8b5cf6',
  glow_color varchar(255) not null default '#3b82f6',
  dark_bg varchar(255) not null default '#0a0a1a',
  light_bg varchar(255) not null default '#ffffff',
  glass_effect boolean not null default true,
  animation_speed varchar(255) not null default 'normal',
  typography varchar(255) not null default 'inter',
  border_radius varchar(255) not null default '0.5rem',
  dark_mode boolean not null default true,
  custom_css jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.galleries (
  id bigint generated by default as identity primary key,
  title varchar(255) not null,
  slug varchar(255) not null unique,
  description text,
  cover_image varchar(255),
  images jsonb,
  category varchar(255),
  location varchar(255),
  event_date date,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

/* ---- supabase\02-indexes-storage.sql ---- */

-- Porto CMS — Supabase Schema — Part 2: Indexes, Storage, RLS

-- Indexes
create index if not exists activity_logs_user_id_index on public.activity_logs (user_id);
create index if not exists activity_logs_subject_type_subject_id_index on public.activity_logs (subject_type, subject_id);
create index if not exists projects_status_index on public.projects (status);
create index if not exists posts_status_index on public.posts (status);
create index if not exists posts_published_at_index on public.posts (published_at desc);
create index if not exists menus_sort_order_index on public.menus (sort_order);
create index if not exists skills_sort_order_index on public.skills (sort_order);
create index if not exists experiences_sort_order_index on public.experiences (sort_order);
create index if not exists education_sort_order_index on public.education (sort_order);
create index if not exists certificates_sort_order_index on public.certificates (sort_order);
create index if not exists social_media_sort_order_index on public.social_media (sort_order);
create index if not exists translations_locale_index on public.translations (locale);
create index if not exists media_created_at_index on public.media (created_at desc);
create index if not exists activity_logs_created_at_index on public.activity_logs (created_at desc);
create index if not exists galleries_sort_order_index on public.galleries (sort_order);
create index if not exists prompts_slug_index on public.prompts (slug);

-- Storage buckets
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('backups', 'backups', false)
on conflict (id) do nothing;

-- RLS: tables only accessed via Next.js server (service role), so RLS is disabled by default.
-- Storage public bucket 'media' is readable by everyone (public images).

alter table public.users enable row level security;
alter table public.settings enable row level security;
alter table public.hero_sections enable row level security;
alter table public.about_sections enable row level security;
alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.experiences enable row level security;
alter table public.education enable row level security;
alter table public.certificates enable row level security;
alter table public.posts enable row level security;
alter table public.social_media enable row level security;
alter table public.menus enable row level security;
alter table public.translations enable row level security;
alter table public.prompts enable row level security;
alter table public.media enable row level security;
alter table public.activity_logs enable row level security;
alter table public.seos enable row level security;
alter table public.themes enable row level security;
alter table public.galleries enable row level security;

-- Public read access (website content is public)
-- CATATAN KEAMANAN: users/settings/activity_logs TIDAK diberi policy publik
-- (berisi hash password, API key, dan IP). Semua akses via service role.
create policy "public_read_hero" on public.hero_sections for select using (true);
create policy "public_read_about" on public.about_sections for select using (true);
create policy "public_read_projects" on public.projects for select using (true);
create policy "public_read_skills" on public.skills for select using (true);
create policy "public_read_experiences" on public.experiences for select using (true);
create policy "public_read_education" on public.education for select using (true);
create policy "public_read_certificates" on public.certificates for select using (true);
create policy "public_read_posts" on public.posts for select using (true);
create policy "public_read_social" on public.social_media for select using (true);
create policy "public_read_menus" on public.menus for select using (true);
create policy "public_read_translations" on public.translations for select using (true);
create policy "public_read_prompts" on public.prompts for select using (true);
create policy "public_read_media" on public.media for select using (true);
create policy "public_read_seos" on public.seos for select using (true);
create policy "public_read_themes" on public.themes for select using (true);
create policy "public_read_galleries" on public.galleries for select using (true);

-- Storage policies
create policy "public_read_media_bucket" on storage.objects for select using (bucket_id = 'media');
create policy "public_read_backups_bucket" on storage.objects for select using (bucket_id = 'backups' and (auth.role() = 'authenticated'));

/* ---- supabase\03-seed.sql ---- */

-- Porto CMS Seed - dihasilkan dari porto_cms_dump.sql
-- Jalankan setelah 01-tables.sql dan 02-indexes-storage.sql

insert into public."users" ("id", "name", "username", "email", "email_verified_at", "password", "remember_token", "created_at", "updated_at") values
(1, 'Faiz Indriaswara', 'faizindriaswara', 'owner@example.com', NULL, '$2y$12$x5lH/agVdczn.Kx0Kj5VcOC7h6qcCCW2mNlBwJcTvQJ7F6.6ZDsXy', NULL, '2026-08-04 21:28:14', '2026-08-06 21:48:10')
on conflict do nothing;

insert into public."about_sections" ("id", "photo", "description", "quote", "statistics", "skills", "is_active", "created_at", "updated_at") values
(1, NULL, 'Saya adalah seorang developer yang bersemangat dalam membangun solusi digital. Berpengalaman dalam pengembangan web fullstack dengan fokus pada backend menggunakan Laravel.', 'Code is poetry in motion.', '[{"label":"Projects","value":10},{"label":"Years","value":3},{"label":"Clients","value":8},{"label":"Cups of Coffee","value":999}]', '["PHP","Laravel","JavaScript","Vue.js","MySQL","Tailwind CSS"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14')
on conflict do nothing;

insert into public."activity_logs" ("id", "user_id", "action", "subject_type", "subject_id", "properties", "description", "ip_address", "user_agent", "created_at", "updated_at") values
(1, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'curl/8.21.0', '2026-08-04 22:31:45', '2026-08-04 22:31:45'),
(2, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'curl/8.21.0', '2026-08-04 22:41:44', '2026-08-04 22:41:44'),
(3, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'curl/8.21.0', '2026-08-04 22:42:12', '2026-08-04 22:42:12'),
(4, 1, 'create_skill', 'App\Models\Skill', 8, NULL, 'Skill ditambahkan: Python', NULL, NULL, '2026-08-04 22:42:12', '2026-08-04 22:42:12'),
(5, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'curl/8.21.0', '2026-08-04 23:43:24', '2026-08-04 23:43:24'),
(6, 1, 'create_skill', 'App\Models\Skill', 9, NULL, 'Skill ditambahkan: Python', NULL, NULL, '2026-08-04 23:43:44', '2026-08-04 23:43:44'),
(7, 1, 'update_skill', 'App\Models\Skill', 8, NULL, 'Skill diperbarui: Python (Pro)', NULL, NULL, '2026-08-04 23:44:09', '2026-08-04 23:44:09'),
(8, 1, 'delete_skill', 'App\Models\Skill', 8, NULL, 'Skill dihapus: Python (Pro)', NULL, NULL, '2026-08-04 23:44:10', '2026-08-04 23:44:10'),
(9, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36', '2026-08-04 23:48:16', '2026-08-04 23:48:16'),
(10, 1, 'upload_media', NULL, NULL, NULL, '1 file diunggah', NULL, NULL, '2026-08-05 00:07:08', '2026-08-05 00:07:08'),
(11, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:31:02', '2026-08-05 00:31:02'),
(12, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:31:59', '2026-08-05 00:31:59'),
(13, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:34:04', '2026-08-05 00:34:04'),
(14, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:34:52', '2026-08-05 00:34:52'),
(15, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:35:40', '2026-08-05 00:35:40'),
(16, 1, 'update_hero', 'App\Models\HeroSection', 1, NULL, 'Hero section diperbarui', NULL, NULL, '2026-08-05 00:42:17', '2026-08-05 00:42:17'),
(17, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36', '2026-08-05 04:13:07', '2026-08-05 04:13:07'),
(18, 1, 'create_social', 'App\Models\SocialMedia', 5, NULL, 'Media sosial ditambahkan: github', NULL, NULL, '2026-08-05 04:43:01', '2026-08-05 04:43:01'),
(19, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36', '2026-08-06 18:02:42', '2026-08-06 18:02:42'),
(20, 1, 'create_project', 'App\Models\Project', 4, NULL, 'Project dibuat: Aplikasi MyFilm', NULL, NULL, '2026-08-06 18:08:22', '2026-08-06 18:08:22'),
(21, 1, 'delete_project', 'App\Models\Project', 3, NULL, 'Project dihapus: Dashboard Analitik Real-time', NULL, NULL, '2026-08-06 18:09:08', '2026-08-06 18:09:08'),
(22, 1, 'update_project', 'App\Models\Project', 4, NULL, 'Project diperbarui: Aplikasi MyFilm', NULL, NULL, '2026-08-06 18:09:25', '2026-08-06 18:09:25'),
(23, 1, 'create_project', 'App\Models\Project', 5, NULL, 'Project dibuat: Web Kecamatan', NULL, NULL, '2026-08-06 18:11:41', '2026-08-06 18:11:41'),
(24, 1, 'logout', NULL, NULL, NULL, 'Owner signed out', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36', '2026-08-06 21:42:34', '2026-08-06 21:42:34'),
(25, 1, 'login', NULL, NULL, NULL, 'Owner signed in', '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36', '2026-08-06 22:06:59', '2026-08-06 22:06:59')
on conflict do nothing;

insert into public."certificates" ("id", "title", "issuer", "issue_date", "expiry_date", "description", "file", "image", "credential_id", "credential_url", "sort_order", "is_active", "created_at", "updated_at") values
(1, 'Laravel Certification', 'Laravel Institute', '2023-03-15', NULL, 'Sertifikasi resmi pengembangan aplikasi dengan framework Laravel.', NULL, NULL, 'LAR-2023-001', 'https://example.com/cert/laravel', 1, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(2, 'Machine Learning Specialization', 'Coursera', '2022-08-20', NULL, 'Spesialisasi machine learning dengan Python dan TensorFlow.', NULL, NULL, 'ML-2022-089', 'https://example.com/cert/ml', 2, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57')
on conflict do nothing;

insert into public."education" ("id", "institution", "degree", "field_of_study", "start_date", "end_date", "is_current", "description", "sort_order", "is_active", "created_at", "updated_at") values
(1, 'Universitas Indonesia', 'S.Kom', 'Ilmu Komputer', '2017-08-01', '2021-07-31', false, 'Fokus pada rekayasa perangkat lunak dan kecerdasan buatan.', 1, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(2, 'Dicoding Academy', 'Sertifikasi', 'Backend Developer', '2021-01-01', '2021-05-01', false, 'Belajar Laravel dan pengembangan API.', 2, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(3, 'STT Wastukancana', 'S.Kom', 'Teknik Informatika', '2017-08-01', '2021-07-31', false, 'Fokus pada rekayasa perangkat lunak dan kecerdasan buatan.', 1, true, '2026-08-05 00:33:15', '2026-08-05 00:33:15')
on conflict do nothing;

insert into public."experiences" ("id", "title", "company", "location", "start_date", "end_date", "is_current", "description", "achievements", "sort_order", "is_active", "created_at", "updated_at") values
(1, 'Fullstack Developer', 'PT Tech Nusantara', 'Jakarta, Indonesia', '2023-01-01', NULL, true, 'Mengembangkan aplikasi web fullstack menggunakan Laravel dan Vue.js, memimpin tim kecil, dan mengoptimalkan performa aplikasi hingga 40%.', '["Meningkatkan performa aplikasi sebesar 40%","Memimpin tim 4 developer","Mengimplementasikan CI\/CD pipeline"]', 1, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(2, 'Backend Developer', 'Startup Digital Kreatif', 'Bandung, Indonesia', '2021-06-01', '2022-12-31', false, 'Membangun REST API dan integrasi pembayaran untuk platform layanan digital.', '["Membangun 20+ endpoint API","Integrasi 3 payment gateway"]', 2, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57')
on conflict do nothing;

insert into public."hero_sections" ("id", "name", "subtitle", "typing_texts", "description", "background_type", "background_value", "background_image", "photo", "buttons", "social_media", "is_active", "created_at", "updated_at") values
(1, 'Faiz Indriaswara', 'Fullstack Developer & AI Enthusiast', '["Fullstack Developer","Laravel Expert","AI Enthusiast","Problem Solver"]', 'Saya membangun aplikasi web modern, cepat, dan scalable menggunakan Laravel & AI.', 'gradient', 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', NULL, 'media/hero/syORpWkO0uehqdy3pYFjDK7sn3kSwNWzVYzFlk8V.jpg', '[{"label":"Lihat Projects","url":"#projects","style":"primary"},{"label":"Hubungi Saya","url":"#contact","style":"ghost"}]', '["github","linkedin","instagram"]', true, '2026-08-04 21:28:14', '2026-08-05 00:42:17')
on conflict do nothing;

insert into public."media" ("id", "name", "file_path", "file_type", "mime_type", "file_size", "disk", "collection", "metadata", "created_at", "updated_at") values
(1, 'profile.jpg', 'media/general/DHvTuSqFBt8PRf6m1hQXWwhnvM7Iojc6tGjK393X.jpg', 'image', 'image/jpeg', 18781, 'public', 'general', '[]', '2026-08-05 00:07:08', '2026-08-05 00:07:08')
on conflict do nothing;

insert into public."menus" ("id", "name", "slug", "url", "icon", "parent_id", "sort_order", "is_active", "is_hidden", "created_at", "updated_at") values
(1, 'Beranda', 'home', '/', 'home', NULL, 1, true, false, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(2, 'Tentang', 'about', '#about', 'user', NULL, 2, true, false, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(3, 'Projects', 'projects', '#projects', 'folder', NULL, 3, true, false, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(4, 'Pengalaman', 'experience', '#experience', 'briefcase', NULL, 4, true, false, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(5, 'Sertifikat', 'certificates', '#certificates', 'award', NULL, 5, true, false, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(6, 'Blog', 'blog', '/blog', 'book', NULL, 7, true, false, '2026-08-04 21:28:14', '2026-08-06 19:47:59'),
(7, 'Hubungi', 'contact', '#contact', 'mail', NULL, 8, true, false, '2026-08-04 21:28:14', '2026-08-06 19:47:59'),
(8, 'Gallery', 'gallery', '/gallery', 'camera', NULL, 6, true, false, '2026-08-06 19:47:58', '2026-08-06 19:47:58')
on conflict do nothing;

insert into public."posts" ("id", "title", "slug", "excerpt", "content", "cover_image", "tags", "category", "status", "featured", "seo", "published_at", "created_at", "updated_at") values
(1, 'Membangun CMS AI-First dengan Laravel', 'membangun-cms-ai-first-laravel', 'Bagaimana AI mengubah cara kita mengelola konten website. Pelajari cara membangun CMS yang terintegrasi dengan AI assistant.', '## PendahuluannnAI-First CMS adalah pendekatan baru dalam pengelolaan konten website di mana asisten AI menjadi bagian inti dari alur kerja.nn## Kenapa AI-First?nn1. **Efisiensi** â€” AI membantu menulis dan mengedit konten lebih cepatn2. **Konsistensi** â€” Gaya tulisan tetap terjagan3. **SEO Otomatis** â€” Meta title dan description dibuat otomatisnn## KesimpulannnDengan mengintegrasikan OpenRouter AI ke dalam Laravel, pengelolaan konten menjadi jauh lebih mudah dan powerful.', NULL, '["laravel","ai","cms"]', 'Web Development', 'published', true, NULL, '2026-08-03 20:17:32', '2026-08-04 22:40:57', '2026-08-06 20:17:32'),
(2, 'Tips Optimasi Query MySQL untuk Aplikasi Skala Besar', 'tips-optimasi-query-mysql', 'Pelajari teknik index, query caching, dan best practice optimasi database agar aplikasi tetap cepat saat data membesar.', '## IndexingnnIndex memungkinkan database menemukan data dengan cepat. Gunakan index pada kolom yang sering dipakai di WHERE dan JOIN.nn## Query Optimizationnn- Gunakan EXPLAIN untuk menganalisis queryn- Hindari SELECT * dan ambil kolom yang dibutuhkan sajan- Gunakan eager loading di ORMnn## CachingnnCache hasil query yang jarang berubah menggunakan Redis untuk mempercepat response.', NULL, '["mysql","database","performance"]', 'Database', 'published', false, NULL, '2026-07-30 20:17:32', '2026-08-04 22:40:57', '2026-08-06 20:17:32')
on conflict do nothing;

insert into public."projects" ("id", "title", "slug", "description", "tech_stack", "category", "thumbnail", "thumbnail_prompt", "github_url", "live_url", "status", "featured", "seo", "tags", "created_at", "updated_at") values
(1, 'Porto CMS â€” AI Portfolio Platform', 'porto-cms', 'CMS portfolio modern berbasis Laravel dengan AI assistant terintegrasi untuk mengelola hero, projects, blog, SEO, dan theme tanpa coding.', '["Laravel","Tailwind CSS","OpenRouter AI","MySQL"]', 'Web App', NULL, NULL, 'https://github.com/', NULL, 'published', true, NULL, '["cms","laravel","ai"]', '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(2, 'API E-Commerce dengan Laravel', 'api-ecommerce', 'RESTful API untuk platform e-commerce dengan autentikasi JWT, manajemen produk, keranjang, dan sistem pembayaran.', '["Laravel","MySQL","JWT","REST API"]', 'Backend', NULL, NULL, 'https://github.com/', NULL, 'published', true, NULL, '["api","ecommerce","backend"]', '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(4, 'Aplikasi MyFilm', 'aplikasi-myfilm', 'Implementasi dari cloud computing menggunakan API menggunakan Android Studio', NULL, 'Mobile App', 'media/projects/Ud9H0TyuVJVfV2DfvPHfVHlg4za8Ld5ZFIiMSGk3.png', NULL, 'https://github.com/Izaswara/MyFilm', NULL, 'published', true, NULL, '["[Android Studio","API]"]', '2026-08-06 18:08:22', '2026-08-06 18:09:25'),
(5, 'Web Kecamatan', 'web-kecamatan', 'Website kecamatan yang menampilkan informasi dari kecamatan yang menggunakan Laravel 10', '["Laravel","js","MySql"]', 'Website', NULL, NULL, 'https://github.com/Izaswara/WEB-UAS-KEC', NULL, 'published', true, NULL, '["Website"]', '2026-08-06 18:11:41', '2026-08-06 18:11:41'),
(6, 'Dashboard Analitik Real-time', 'dashboard-analitik', 'Dashboard analitik untuk memvisualisasikan data penjualan secara real-time dengan grafik interaktif dan laporan otomatis.', '["Vue.js","Laravel","Charts.js","WebSocket"]', 'Dashboard', NULL, NULL, 'https://github.com/', NULL, 'published', false, NULL, '["dashboard","analytics","vue"]', '2026-08-06 19:47:59', '2026-08-06 19:47:59')
on conflict do nothing;

insert into public."prompts" ("id", "name", "slug", "prompt_text", "category", "variables", "is_active", "created_at", "updated_at") values
(1, 'Improve Writing', 'improve-writing', 'Please improve the following text to make it more professional, clear, and engaging. Fix any grammar or spelling errors while preserving the original meaning. Return only the improved text.', 'editor', '["text"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(2, 'Generate Project Description', 'generate-project-description', 'Write a compelling project description based on this title and tech stack. Include the problem, solution, and impact. Return as JSON with keys: description, tags.', 'project', '["title","tech_stack"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(3, 'Write Blog Article', 'write-blog-article', 'Write a detailed, well-structured blog article about {topic}. Include an engaging introduction, subheadings, and a conclusion. Return the article in HTML format.', 'blog', '["topic"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(4, 'SEO Meta Tags', 'seo-meta', 'Generate SEO meta tags for {title}. Return JSON with keys: meta_title (max 60 chars), meta_description (max 160 chars), meta_keywords (comma separated), slug.', 'seo', '["title"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(5, 'Generate Experience Description', 'generate-experience', 'Write a professional work experience description for role {title} at {company}. Highlight achievements with measurable results. Return as JSON with keys: description, achievements (array of 3-5 bullets).', 'experience', '["title","company"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(6, 'Generate Skill Description', 'generate-skill', 'Write a short, professional description for the skill "{skill}". Mention where it is commonly used and its value. Max 2 sentences.', 'skill', '["skill"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(7, 'Generate Image Prompt', 'generate-image-prompt', 'Create a detailed AI image generation prompt for: {subject}. Include style, lighting, colors, composition, and mood. Max 100 words, in English.', 'image', '["subject"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(8, 'Translate Text', 'translate-text', 'Translate the following text to {language}. Keep the tone and meaning. Return only the translated text.', 'translation', '["text","language"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(9, 'Summarize Article', 'summarize-article', 'Summarize the following article into {length} concise key points. Return as a JSON array of strings.', 'blog', '["text","length"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(10, 'Generate FAQ', 'generate-faq', 'Generate a list of {count} common questions and answers about: {topic}. Return as JSON array with keys: question, answer.', 'general', '["topic","count"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(11, 'Generate Timeline', 'generate-timeline', 'Generate a career/education timeline from these experiences. Return as JSON array with keys: date, title, description.', 'experience', '["experiences"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(12, 'Resume Summary', 'resume-summary', 'Write a compelling professional summary (max 150 words) for a CV based on these details: {details}.', 'general', '["details"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(13, 'Generate Caption', 'generate-caption', 'Write a catchy social media caption about {topic} with relevant hashtags. Provide 3 options.', 'general', '["topic"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(14, 'Casual Rewrite', 'casual-rewrite', 'Rewrite the following text in a friendly, casual tone while keeping the message clear. Return only the rewritten text.', 'editor', '["text"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(15, 'Formal Rewrite', 'formal-rewrite', 'Rewrite the following text in a professional, formal tone. Return only the rewritten text.', 'editor', '["text"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(16, 'Humanize Text', 'humanize-text', 'Rewrite the following text so it sounds more natural and human, less AI-generated. Return only the rewritten text.', 'editor', '["text"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(17, 'Generate Education Description', 'generate-education', 'Write a professional description for this education entry: {degree} at {institution}. Return as JSON with key: description.', 'education', '["degree","institution"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(18, 'Certificate Description', 'certificate-description', 'Write a short description for this certificate: {title} from {issuer}. Emphasize the skills gained. Max 2 sentences.', 'certificate', '["title","issuer"]', true, '2026-08-04 21:28:14', '2026-08-04 21:28:14')
on conflict do nothing;

insert into public."settings" ("id", "key", "value", "group", "created_at", "updated_at") values
(1, 'site_name', 'Faiz Dev', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(2, 'site_logo', NULL, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(3, 'site_favicon', NULL, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(4, 'site_email', 'owner@example.com', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(5, 'site_phone', +6281234567890, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(6, 'site_address', 'Indonesia', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(7, 'site_footer', 'Â© 2025 Faiz Indriaswara. Built with Laravel & AI.', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(8, 'analytics_google', NULL, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(9, 'search_console', NULL, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(10, 'gtm_code', NULL, 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(11, 'openrouter_api_key', '', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(12, 'openrouter_model', 'openai/gpt-4o-mini', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14'),
(13, 'ai_cms_name', 'Faiz AI CMS', 'general', '2026-08-04 21:28:14', '2026-08-04 21:28:14')
on conflict do nothing;

insert into public."skills" ("id", "name", "icon", "category", "description", "level", "sort_order", "is_active", "created_at", "updated_at") values
(1, 'PHP', 'ðŸ˜', 'Backend', NULL, 92, 1, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(2, 'Laravel', 'ðŸš€', 'Backend', NULL, 90, 2, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(3, 'JavaScript', 'âš¡', 'Frontend', NULL, 85, 3, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(4, 'Vue.js', 'ðŸ’š', 'Frontend', NULL, 82, 4, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(5, 'MySQL', 'ðŸ—„ï¸', 'Database', NULL, 88, 5, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(6, 'Tailwind CSS', 'ðŸŽ¨', 'Frontend', NULL, 90, 6, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57'),
(7, 'Git', 'ðŸŒ¿', 'Tools', NULL, 86, 7, true, '2026-08-04 22:40:57', '2026-08-04 22:40:57')
on conflict do nothing;

insert into public."social_media" ("id", "platform", "url", "icon", "sort_order", "is_active", "created_at", "updated_at") values
(6, 'Github', 'https://github.com/', 'github', 1, true, '2026-08-06 19:47:59', '2026-08-06 19:47:59'),
(7, 'LinkedIn', 'https://linkedin.com/', 'linkedin', 2, true, '2026-08-06 19:47:59', '2026-08-06 19:47:59'),
(8, 'Instagram', 'https://instagram.com/', 'instagram', 3, true, '2026-08-06 19:47:59', '2026-08-06 19:47:59'),
(9, 'Email', 'mailto:owner@example.com', 'mail', 4, true, '2026-08-06 19:47:59', '2026-08-06 19:47:59')
on conflict do nothing;

insert into public."themes" ("id", "name", "is_active", "primary_color", "secondary_color", "accent_color", "gradient_start", "gradient_end", "glow_color", "dark_bg", "light_bg", "glass_effect", "animation_speed", "typography", "border_radius", "dark_mode", "custom_css", "created_at", "updated_at") values
(1, 'Firefly Crimson', true, '#ff3b4e', '#ff7a3d', '#ffd166', '#1a0710', '#2b0f14', '#ff3b4e', '#0a0508', '#fdf1f2', true, 'fast', 'Space Grotesk', '14px', true, NULL, '2026-08-04 21:28:14', '2026-08-05 01:32:28')
on conflict do nothing;

insert into public."translations" ("id", "locale", "group", "key", "value", "is_synced", "created_at", "updated_at") values
(1, 'id', '*', 'menu.home', 'Beranda', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(2, 'id', '*', 'menu.about', 'Tentang', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(3, 'id', '*', 'menu.projects', 'Projects', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(4, 'id', '*', 'menu.experience', 'Pengalaman', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(5, 'id', '*', 'menu.certificates', 'Sertifikat', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(6, 'id', '*', 'menu.gallery', 'Gallery', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(7, 'id', '*', 'menu.blog', 'Blog', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(8, 'id', '*', 'menu.contact', 'Hubungi', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(9, 'id', '*', 'home.portfolio', 'Portfolio', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(10, 'id', '*', 'home.hi', 'Halo, saya', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(11, 'id', '*', 'home.scroll', 'Scroll', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(12, 'id', '*', 'home.contact_me', 'Hubungi Saya', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(13, 'id', '*', 'home.view_all', 'Lihat semua', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(14, 'id', '*', 'about.title', 'Tentang', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(15, 'id', '*', 'about.me', 'Saya', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(16, 'id', '*', 'skills.title', 'Skills &', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(17, 'id', '*', 'skills.tools', 'Tools', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(18, 'id', '*', 'skills.desc', 'Teknologi yang saya kuasai', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(19, 'id', '*', 'projects.title', 'Featured', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(20, 'id', '*', 'projects.subtitle', 'Projects', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(21, 'id', '*', 'projects.desc', 'Beberapa project terbaru saya', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(22, 'id', '*', 'experience.title', 'Pengalaman', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(23, 'id', '*', 'experience.work', 'Kerja', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(24, 'id', '*', 'education.title', 'Pendidikan', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(25, 'id', '*', 'certificates.title', 'Sertifikat', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(26, 'id', '*', 'blog.title', 'Terbaru', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(27, 'id', '*', 'blog.subtitle', 'Posts', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(28, 'id', '*', 'blog.desc', 'Artikel dan tulisan terbaru', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(29, 'id', '*', 'gallery.title', 'Photo', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(30, 'id', '*', 'gallery.subtitle', 'Gallery', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(31, 'id', '*', 'gallery.desc', 'Dokumentasi pekerjaan & pengalaman', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(32, 'id', '*', 'contact.title', 'Let's', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(33, 'id', '*', 'contact.subtitle', 'Connect', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(34, 'id', '*', 'contact.desc', 'Punya proyek atau pertanyaan? Jangan ragu untuk menghubungi saya.', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(35, 'id', '*', 'connect.email', 'Email Me', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(36, 'en', '*', 'menu.home', 'Home', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(37, 'en', '*', 'menu.about', 'About', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(38, 'en', '*', 'menu.projects', 'Projects', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(39, 'en', '*', 'menu.experience', 'Experience', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(40, 'en', '*', 'menu.certificates', 'Certificates', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(41, 'en', '*', 'menu.gallery', 'Gallery', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(42, 'en', '*', 'menu.blog', 'Blog', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(43, 'en', '*', 'menu.contact', 'Contact', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(44, 'en', '*', 'home.portfolio', 'Portfolio', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(45, 'en', '*', 'home.hi', 'Hi, I'm', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(46, 'en', '*', 'home.scroll', 'Scroll', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(47, 'en', '*', 'home.contact_me', 'Contact Me', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(48, 'en', '*', 'home.view_all', 'View all', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(49, 'en', '*', 'about.title', 'About', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(50, 'en', '*', 'about.me', 'Me', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(51, 'en', '*', 'skills.title', 'Skills &', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(52, 'en', '*', 'skills.tools', 'Tools', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(53, 'en', '*', 'skills.desc', 'Technologies I master', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(54, 'en', '*', 'projects.title', 'Featured', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(55, 'en', '*', 'projects.subtitle', 'Projects', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(56, 'en', '*', 'projects.desc', 'Some of my latest projects', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(57, 'en', '*', 'experience.title', 'Work', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(58, 'en', '*', 'experience.work', 'Experience', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(59, 'en', '*', 'education.title', 'Education', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(60, 'en', '*', 'certificates.title', 'Certificates', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(61, 'en', '*', 'blog.title', 'Latest', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(62, 'en', '*', 'blog.subtitle', 'Posts', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(63, 'en', '*', 'blog.desc', 'Recent articles and writings', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(64, 'en', '*', 'gallery.title', 'Photo', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(65, 'en', '*', 'gallery.subtitle', 'Gallery', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(66, 'en', '*', 'gallery.desc', 'Documentation of work & experiences', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(67, 'en', '*', 'contact.title', 'Let's', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(68, 'en', '*', 'contact.subtitle', 'Connect', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(69, 'en', '*', 'contact.desc', 'Have a project or question? Feel free to contact me.', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(70, 'en', '*', 'connect.email', 'Email Me', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(71, 'ja', '*', 'menu.home', 'ãƒ›ãƒ¼ãƒ ', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(72, 'ja', '*', 'menu.about', 'ç§ã«ã¤ã„ã¦', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(73, 'ja', '*', 'menu.projects', 'ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(74, 'ja', '*', 'menu.experience', 'çµŒé¨“', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(75, 'ja', '*', 'menu.certificates', 'è³‡æ ¼', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(76, 'ja', '*', 'menu.gallery', 'ã‚®ãƒ£ãƒ©ãƒªãƒ¼', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(77, 'ja', '*', 'menu.blog', 'ãƒ–ãƒ­ã‚°', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(78, 'ja', '*', 'menu.contact', 'ãŠå•ã„åˆã‚ã›', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(79, 'ja', '*', 'home.portfolio', 'ãƒãƒ¼ãƒˆãƒ•ã‚©ãƒªã‚ª', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(80, 'ja', '*', 'home.hi', 'ã“ã‚“ã«ã¡ã¯', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(81, 'ja', '*', 'home.scroll', 'ã‚¹ã‚¯ãƒ­ãƒ¼ãƒ«', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(82, 'ja', '*', 'home.contact_me', 'ãŠå•ã„åˆã‚ã›', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(83, 'ja', '*', 'home.view_all', 'ã™ã¹ã¦è¦‹ã‚‹', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(84, 'ja', '*', 'about.title', 'ç§ã«ã¤ã„ã¦', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(85, 'ja', '*', 'about.me', '', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(86, 'ja', '*', 'skills.title', 'ã‚¹ã‚­ãƒ«&', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(87, 'ja', '*', 'skills.tools', 'ãƒ„ãƒ¼ãƒ«', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(88, 'ja', '*', 'skills.desc', 'ç§ãŒå¾—æ„ã¨ã™ã‚‹æŠ€è¡“', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(89, 'ja', '*', 'projects.title', 'æ³¨ç›®', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(90, 'ja', '*', 'projects.subtitle', 'ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(91, 'ja', '*', 'projects.desc', 'æœ€è¿‘ã®ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆ', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(92, 'ja', '*', 'experience.title', 'è·æ­´', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(93, 'ja', '*', 'experience.work', '', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(94, 'ja', '*', 'education.title', 'å­¦æ­´', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(95, 'ja', '*', 'certificates.title', 'è³‡æ ¼', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(96, 'ja', '*', 'blog.title', 'æœ€æ–°', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(97, 'ja', '*', 'blog.subtitle', 'è¨˜äº‹', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(98, 'ja', '*', 'blog.desc', 'æœ€è¿‘ã®è¨˜äº‹', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(99, 'ja', '*', 'gallery.title', 'ãƒ•ã‚©ãƒˆ', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(100, 'ja', '*', 'gallery.subtitle', 'ã‚®ãƒ£ãƒ©ãƒªãƒ¼', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(101, 'ja', '*', 'gallery.desc', 'ä»•äº‹ã¨çµŒé¨“ã®è¨˜éŒ²', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(102, 'ja', '*', 'contact.title', 'ã¤ãªãŒã‚Š', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(103, 'ja', '*', 'contact.subtitle', '', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(104, 'ja', '*', 'contact.desc', 'ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆã‚„è³ªå•ãŒã‚ã‚Œã°ã€ãŠæ°—è»½ã«ã”é€£çµ¡ãã ã•ã„ã€‚', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32'),
(105, 'ja', '*', 'connect.email', 'ãƒ¡ãƒ¼ãƒ«', true, '2026-08-06 20:17:32', '2026-08-06 20:17:32')
on conflict do nothing;


/* ---- supabase\04-contact-views.sql ---- */

-- View counters untuk project & artikel
alter table public.projects add column if not exists views integer not null default 0;
alter table public.posts add column if not exists views integer not null default 0;

-- Pesan dari form kontak publik
create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null,
  subject varchar(200),
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz default now()
);

alter table public.contacts enable row level security;

create index if not exists contacts_created_at_index on public.contacts (created_at desc);
create index if not exists projects_views_index on public.projects (views desc);
create index if not exists posts_views_index on public.posts (views desc);
